var scene_detail_list={
	"topo":[
		{
			"name":"backend1",	
			"uuid":0,
			"children":null,
			"type":"node"
		},
		{
			"name":"server",	
			"uuid":0,
			"children":[{
							"name":"broadcast",	
							"uuid":0,
							"type":"plugin"
						},
						{
							"name":"login_verify",	
							"uuid":0,
							"type":"plugin"
						},
						{
							"name":"friend_list",	
							"uuid":0,
							"type":"plugin"
						},
						{
							"name":"Paths",
							"children":[
										{
											"type":"hh",
											"subtype":"hh",
											"Edges":[{"from":"ws_port","to":"login_verify"},
													 {"from":"login_verify","to":"login_verify"},
												     {"from":"login_verify","to":"friend_list"}
												    ]
										},
	
										{
											"type":"yy",
											"subtype":"yy",
											"Edges":[{"from":"friend_list","to":"login_verify"},
													 {"from":"login_verify","to":"login_verify"},
												     {"from":"login_verify","to":"ws_port"}
												    ]
										}
										]

						}],
			"type":"node"
		},
		{
			"name":"backend2",	
			"uuid":0,
			"children":null,
			"type":"node"
		},
		{
			"name":"Edges",
			"children":[
						{"from":"backend1","to":"server"},
						{"from":"server","to":"backend2"}
					   ]
		}
		],
	"topo1":[]
}